---
- name: Install Fog Project on Rocky Linux using Docker
  hosts: rocky_server
  become: true
  tasks:

    # Step 1: Update all packages
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    # Step 2: Install dependencies (Docker and Docker-compose)
    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-compose
      dnf:
        name: docker-compose
        state: present

    # Step 3: Pull the Fog Project Docker image
    - name: Pull Fog Project Docker image
      docker_image:
        name: redvex2460/fogproject
        tag: latest
        source: pull

    # Step 4: Run Fog Project Docker container
    - name: Run Fog Project container
      docker_container:
        name: fogproject_container
        image: redvex2460/fogproject:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
          - "443:443"  # Expose the necessary ports (example: HTTP and HTTPS)
        volumes:
          - /fogproject-data:/var/www/fog  # Volume mapping for persistent data

    # Step 5: Verify that the Fog Project container is running
    - name: Check if Fog Project container is running
      docker_container:
        name: fogproject_container
        state: started
      register: container_status

    - name: Show container status
      debug:
        msg: "Fog Project container is running: {{ container_status }}"
