version: '3.8'
services:
  fogproject:
    image: redvex2460/fogproject:latest
    container_name: fogproject
    network_mode: host  # Allows container to use host networking for PXE/DHCP
    restart: unless-stopped
    volumes:
      - /fog/data:/var/www/html/fog/data  # Adjust path as necessary for your data persistence needs
    environment:
      - TZ=Europe/Berlin  # Set timezone to Berlin
    logging:
      options:
        max-size: "10m"
        max-file: "3"
