---
- name: Update and upgrade packages on Rocky Linux server
  hosts: rocky
  become: true  # Ensures tasks are run with elevated privileges (root)

  tasks:
    - name: Update all packages with yum
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == 'yum'

    - name: Upgrade all packages with yum, excluding the kernel
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: kernel*
      when: ansible_pkg_mgr == 'yum'

    - name: Display success message
      ansible.builtin.debug:
        msg: "You did it!"
